//---------------------------------------------------------------------
// Name:    Spencer, Dustin, Nick, Daniel, Logan
// Project: Restaurant Kiosk Software
// Purpose: Menu file used to store various Domain Layer classes
//
// *Originally auto generated via Windows SDK Tools using an xml
// that we created from scratch. Since been modified to meet our 
// needs and requirements.
//
//---------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be 
//     lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------

using System.Collections.Generic;
using System.Xml.Serialization;

// ----------------------------------------------------------------
// This source code was auto-generated by xsd, Version=4.6.81.0.
// ----------------------------------------------------------------
namespace RestaurantKiosk
{
    // ----------------------------------------------------------------
    // Partial class to store the List of MenuItems from the xml.
    // this needs to be here for serialization and deserialization.
    // ----------------------------------------------------------------
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Items
    {
        private List<MenuItem> itemsList = new List<MenuItem>();

        // ----------------------------------------------------------------
        // Holds the list of Menu Items
        // ----------------------------------------------------------------
        [System.Xml.Serialization.XmlElementAttribute("MenuItem", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<MenuItem> ItemsList
        {
            get
            {
                return this.itemsList;
            }
            set
            {
                this.itemsList = value;
            }
        }
    }

    // ----------------------------------------------------------------
    // Our main object class for different items that get added to the menu.
    // ----------------------------------------------------------------
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MenuItem
    {

        private List<Option> options = new List<Option>();

        private string name;

        private string category;

        private int calories;

        private string description;

        private float price;

        private float timeCost;

        private bool available;

        private string uniqueID;

        // ----------------------------------------------------------------
        // A List of options that the menu item contains.
        // ----------------------------------------------------------------
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Option", typeof(Option), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<Option> Options
        {
            get
            {
                return this.options;
            }
            set
            {
                this.options = value;
            }
        }

        // ----------------------------------------------------------------
        // Name of the Menu Item (Get, Set)
        // ----------------------------------------------------------------
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nameAtt
        {
            get
            {
                return this.name;
            }
            set
            {
                this.name = value;
            }
        }

        // ----------------------------------------------------------------
        // Category of the Menu Item (Get, Set)
        // ----------------------------------------------------------------
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string categoryAtt
        {
            get
            {
                return this.category;
            }
            set
            {
                this.category = value;
            }
        }

        // ----------------------------------------------------------------
        // Calories of the Menu Item (Get, Set)
        // ----------------------------------------------------------------
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int caloriesAtt
        {
            get
            {
                return this.calories;
            }
            set
            {
                this.calories = value;
            }
        }

        // ----------------------------------------------------------------
        // Description of the Menu Item (Get, Set)
        // ----------------------------------------------------------------
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string descriptionAtt
        {
            get
            {
                return this.description;
            }
            set
            {
                this.description = value;
            }
        }

        // ----------------------------------------------------------------
        // Price of the Menu Item (Get, Set)
        // ----------------------------------------------------------------
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float priceAtt
        {
            get
            {
                return this.price;
            }
            set
            {
                this.price = value;
            }
        }

        // ----------------------------------------------------------------
        // Time cost of the Menu Item (Get, Set)
        // ----------------------------------------------------------------
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float timeCostAtt
        {
            get
            {
                return this.timeCost;
            }
            set
            {
                this.timeCost = value;
            }
        }

        // ----------------------------------------------------------------
        // Unique ID of a specific order based Menu Item.
        // ----------------------------------------------------------------
        [XmlIgnore]
        public string uniqueIDAtt
        {
            get
            {
                return this.uniqueID;
            }
            set
            {
                this.uniqueID = value;
            }
        }

        // ----------------------------------------------------------------
        // Empty constructor for Menu Item creation.
        // ----------------------------------------------------------------
        public MenuItem()
        {

        }

        // ----------------------------------------------------------------
        // Full constructor for Menu Item creation.
        // ----------------------------------------------------------------
        public MenuItem(int cal, string desc, string itemName, float itemPrice, float itemTimeCost, string categoryName)
        {
            calories = cal;
            description = desc;
            name = itemName;
            price = itemPrice;
            timeCost = itemTimeCost;
            available = true;
            options = new List<Option>();
            category = categoryName;
        }

        // ----------------------------------------------------------------
        // Adds an option to the Menu Item.
        // ----------------------------------------------------------------
        public void addOption(Option newOption)
        {
            options.Add(newOption);
        }

        // ----------------------------------------------------------------
        // Remove an option from the Menu Item.
        // ----------------------------------------------------------------
        public void removeOption(int index)
        {
            options.RemoveAt(index);
        }

        // ----------------------------------------------------------------
        // Update time cost of the Menu Item.
        // ----------------------------------------------------------------
        public void updatetimeCost(float newTime)
        {
            timeCost = newTime;
        }

        // ----------------------------------------------------------------
        // Returns the option of the Menu Item based on its name.
        // Returns null if not found.
        // ----------------------------------------------------------------
        public Option getOption(string name)
        {
            foreach (Option option in options)
            {
                if (option.nameAtt.Equals(name))
                {
                    return options.Find(x => x.nameAtt == name);
                }
            }
            return null;
        }

        // ----------------------------------------------------------------
        // Returns the size of the list of options.
        // ----------------------------------------------------------------
        public int getOptionsListSize()
        {
            return options.Count;
        }

        // ----------------------------------------------------------------
        // Updates the Menu Item category name.
        // ----------------------------------------------------------------
        public void updateCategory(string newCat)
        {
            category = newCat;
        }
    }

    // ----------------------------------------------------------------
    // Option class is used to further define specific options within
    // a Menu Item.
    // ----------------------------------------------------------------
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class Option
    {

        private string name;

        private string picture;

        private float price;

        private int addedCalories;

        // ----------------------------------------------------------------
        // Name of the Option (Get, Set)
        // ----------------------------------------------------------------
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nameAtt
        {
            get
            {
                return this.name;
            }
            set
            {
                this.name = value;
            }
        }

        // ----------------------------------------------------------------
        // Picture of the Option (Get, Set) (File Location)
        // ----------------------------------------------------------------
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pictureAtt
        {
            get
            {
                return this.picture;
            }
            set
            {
                this.picture = value;
            }
        }

        // ----------------------------------------------------------------
        // Price of the Option (Get, Set)
        // ----------------------------------------------------------------
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float priceAtt
        {
            get
            {
                return this.price;
            }
            set
            {
                this.price = value;
            }
        }

        // ----------------------------------------------------------------
        // Added calories of the Option (Get, Set)
        // ----------------------------------------------------------------
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int addedCaloriesAtt
        {
            get
            {
                return this.addedCalories;
            }
            set
            {
                this.addedCalories = value;
            }
        }

        // ----------------------------------------------------------------
        // Empty Option constructor.
        // ----------------------------------------------------------------
        public Option()
        {

        }

        // ----------------------------------------------------------------
        // Full constructor for the option.
        // ----------------------------------------------------------------
        public Option(string optionName, float optionPrice, int cal)
        {
            name = optionName;
            price = optionPrice;
            addedCalories = cal;
        }
    }
}
